name: Build and Deploy Hugo Site
on:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js for PostCSS/PurgeCSS
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install PostCSS dependencies
      - name: Install PostCSS dependencies
        run: |
          npm install postcss autoprefixer @fullhuman/postcss-purgecss

      # Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true  # Use Hugo Extended for Sass/SCSS processing if needed

      # Build the site
      - name: Build site
        run: |
          # Enable stats to generate hugo_stats.json for PurgeCSS
          hugo --minify --gc --enableGitInfo
        env:
          HUGO_ENVIRONMENT: production

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Hugo's default output directory

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
